trigger:
  branches:
    include:
      - main
      - develop
pool:
  name: 'FCTBL'
  demands:
    - agent.name -equals BLFCT-mv1-SAVIOS-3
variables:
  containerregistrytype: 'Azure Container Registry'
  azureSubscription: 'SAVIA-PRUEBAS'
  azureContainerRegistryLoginServer: 'acriberasi.azurecr.io'
  azureContainerRegistryId: '/subscriptions/6a0bc962-2d61-4d6b-9951-8c49004a41df/resourceGroups/BLFCTS-rg-IberAsi/providers/Microsoft.ContainerRegistry/registries/ACRiberasi'
  dockerComposeFile: 'docker-compose.yml'
  action: 'Run a Docker Compose command'
  devAppServiceName: 'BLFCTS-AppWeb-IberAsi-DEV'
  preAppServiceName: 'BLFCTS-AppWeb-IberAsi-PRE'
  proAppServiceName: 'BLFCTS-AppWeb-IberAsi-PRO'
  resourceGroup: 'BLFCTS-rg-IberAsi'
  dockerRepository: 'triviadosweb'    
  dockerImageTag: $[counter('versionCounter', 1)]
stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build y Push de imagen Docker en ACR'
        steps:
          - task: DockerCompose@0
            displayName: 'Build Docker Imagen con Docker Compose'
            inputs:
              containerregistrytype: '$(containerregistrytype)'
              azureSubscription: '$(azureSubscription)'
              azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryLoginServer)","id":"$(azureContainerRegistryId)"}'
              dockerComposeFile: '$(dockerComposeFile)'
              action: 'Build services'
              additionalImageTags: '$(dockerImageTag)'
              dockerComposeVersion: '2'
          - task: DockerCompose@0
            displayName: 'Push Docker Imagen a ACR'
            inputs:
              containerregistrytype: '$(containerregistrytype)'
              azureSubscription: '$(azureSubscription)'
              azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryLoginServer)","id":"$(azureContainerRegistryId)"}'
              dockerComposeFile: '$(dockerComposeFile)'
              action: 'Push services'
              additionalImageTags: '$(dockerImageTag)'
              dockerComposeVersion: '2'
  - stage: DespliegueDevelop
    displayName: 'Despliegue en DEVELOP'
    jobs:
      - job: DeployToDevelop
        displayName: 'Despliegue en App Service DEVELOP'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              AppName: '$(devAppServiceName)'
              containers: '$(azureContainerRegistryLoginServer)/$(dockerRepository):$(dockerImageTag)'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configurar variables de entorno para DEV'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(devAppServiceName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://acriberasi.azurecr.io",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "ACRiberasi",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "$(ACR_PASSWORD)",
                    "slotSetting": false
                  },
                  {
                    "name": "ConnectionStrings__DefaultConnection",
                    "value": "Server=sqlserversavios.database.windows.net;Database=IberAsi_DEV;User=savios.local;Password=$(STRING_PASSWORD);",
                    "slotSetting": false
                  }
                ]
 
  - stage: DesplieguePre
    displayName: 'Despliegue en PRE'
    condition: and(eq(variables['Build.SourceBranchName'], 'main'), succeeded())
    jobs:
      - job: DeployToPre
        displayName: 'Despliegue en App Service PRE'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              AppName: '$(preAppServiceName)'
              containers: '$(azureContainerRegistryLoginServer)/$(dockerRepository):$(dockerImageTag)'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configurar variables de entorno para PRE'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(preAppServiceName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://acriberasi.azurecr.io",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "ACRiberasi",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "$(ACR_PASSWORD)",
                    "slotSetting": false
                  },
                  {
                    "name": "ConnectionStrings__DefaultConnection",
                    "value": "Server=sqlserversavios.database.windows.net;Database=IberAsi_PRE;User=savios.local;Password=$(STRING_PASSWORD);",
                    "slotSetting": false
                  }
                ]
 
  - stage: DesplieguePro
    displayName: 'Despliegue en PRO'
    condition: and(eq(variables['Build.SourceBranchName'], 'main'), succeeded())
    jobs:
      - job: DeployToPro
        displayName: 'Despliegue en App Service PRO'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              AppName: '$(proAppServiceName)'
              containers: '$(azureContainerRegistryLoginServer)/$(dockerRepository):$(dockerImageTag)'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configurar variables de entorno para PRO'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(proAppServiceName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://acriberasi.azurecr.io",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "ACRiberasi",
                    "slotSetting": false
                  },
                  {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "$(ACR_PASSWORD)",
                    "slotSetting": false
                  },
                  {
                    "name": "ConnectionStrings__DefaultConnection",
                    "value": "Server=sqlserversavios.database.windows.net;Database=IberAsi_PRO;User=savios.local;Password=$(STRING_PASSWORD);",
                    "slotSetting": false
                  }
                ]