// palabras.js
export const TODAS_LAS_PALABRAS = [
  "ALGORITMO", "VARIABLE", "PYTHON", "HTML", "CSS", "JAVASCRIPT", "DEBUG",
  "COMPILAR", "FRAMEWORK", "FUNCION", "GIT", "API", "SQL", "LOOP", "ARRAY",
  "OBJETO", "REACT", "FRONTEND", "BACKEND", "NPM", "NODE", "HOOKS", "TEMPLATE",
  "CLASE", "INTERFAZ", "BROWSER", "DOM", "EVENTO", "ASINCRONO", "PROMESA",
  "MODULO", "IMPORTAR", "EXPORTAR", "VARIABLES", "CONST", "LET", "TIPOS",
  "BOOLEANO", "NUMERO", "CADENA", "OPERADOR", "CONDICIONAL", "BUCLE",
  "ITERACION", "FUNCIONES", "PARAMETRO", "ARGUMENTO", "OBJETIVO", "HERENCIA",
  "POLIMORFISMO", "ENCAPSULAMIENTO", "ESTRUCTURA", "DATOS", "ARCHIVO",
  "SISTEMA", "RED", "SERVIDOR", "CLIENTE", "PROTOCOLO", "HTTP", "HTTPS",
  "FTP", "SSH", "TOKEN", "AUTENTICACION", "AUTORIZACION", "ENCRIPTACION",
  "HASH", "BASEDEDATOS", "SQLITE", "MONGODB", "POSTGRES", "MYSQL", "ORM",
  "APIREST", "JSON", "XML", "CSV", "PARSEO", "DEPURACION", "CONSOLA",
  "VARIABLEGLOBAL", "VARIABLELOCAL", "STACK", "HEAP", "MEMORIA", "OPTIMIZACION",
  "COMPILACION", "INTERPRETE", "SINTAXIS", "SEMANTICA", "DESARROLLO",
  "VERSIONADO", "GITHUB", "GITLAB", "BITBUCKET", "CONTINUO", "INTEGRACION",
  "DESPLIEGUE", "DOCKER", "KUBERNETES", "VIRTUALIZACION", "NUBE", "SERVICIOS"
];
