export interface EntradaPalabra {
  palabra: string;
  pista: string;
}

export const ENTRADAS_PALABRAS: EntradaPalabra[] = [
  { palabra: "ALGORITMO", pista: "Conjunto de pasos finitos para resolver un problema" },
  { palabra: "VARIABLE", pista: "Espacio de memoria que puede cambiar de valor" },
  { palabra: "PYTHON", pista: "Lenguaje de programación con enfoque en legibilidad" },
  { palabra: "HTML", pista: "Lenguaje de marcado para estructurar páginas web" },
  { palabra: "CSS", pista: "Lenguaje de estilos para páginas web" },
  { palabra: "JAVASCRIPT", pista: "Lenguaje de scripting que corre en el navegador" },
  { palabra: "DEBUG", pista: "Proceso de encontrar y corregir errores en el código" },
  { palabra: "COMPILAR", pista: "Traducir código fuente a código máquina" },
  { palabra: "FRAMEWORK", pista: "Conjunto de herramientas y librerías para facilitar el desarrollo" },
  { palabra: "FUNCION", pista: "Bloque de código que realiza una tarea específica" },
  { palabra: "CLASE", pista: "Plantilla para crear objetos en programación orientada a objetos" },
  { palabra: "OBJETO", pista: "Instancia de una clase con propiedades y métodos" },
  { palabra: "HERENCIA", pista: "Mecanismo para crear nuevas clases a partir de otras existentes" },
  { palabra: "INTERFAZ", pista: "Definición de métodos que una clase debe implementar" },
  { palabra: "VARIABLEGLOBAL", pista: "Variable accesible desde cualquier parte del programa" },
  { palabra: "ARRAY", pista: "Estructura de datos para almacenar elementos en orden" },
  { palabra: "BROWSER", pista: "Programa para visualizar páginas web" },
  { palabra: "SERVIDOR", pista: "Computadora que ofrece servicios a otras" },
  { palabra: "API", pista: "Interfaz para que aplicaciones interactúen entre sí" },
  { palabra: "JSON", pista: "Formato ligero para intercambio de datos" },
  { palabra: "BOOLEANO", pista: "Tipo de dato que representa verdadero o falso" },
  { palabra: "CICLO", pista: "Estructura para repetir instrucciones" },
  { palabra: "CONDICIONAL", pista: "Estructura que ejecuta código según una condición" },
  { palabra: "STRING", pista: "Tipo de dato para cadenas de texto" },
  { palabra: "ENTERO", pista: "Tipo de dato para números sin decimales" },
  { palabra: "FLOTANTE", pista: "Número con parte decimal" },
  { palabra: "LAMBDA", pista: "Función anónima o expresión funcional" },
  { palabra: "OBJETIVO", pista: "Meta o propósito en un proyecto" },
  { palabra: "MODULO", pista: "Archivo que contiene código reutilizable" },
  { palabra: "IMPORTAR", pista: "Incluir código de otro módulo" },
  { palabra: "EXPORTAR", pista: "Hacer accesible código desde otro módulo" },
  { palabra: "INTERPRETE", pista: "Programa que ejecuta código línea a línea" },
  { palabra: "CLUSTER", pista: "Agrupación de computadoras trabajando juntas" },
  { palabra: "CONEXION", pista: "Vínculo entre dispositivos o redes" },
  { palabra: "ENCRIPTAR", pista: "Codificar datos para protegerlos" },
  { palabra: "DESENCRIPTAR", pista: "Decodificar datos protegidos" },
  { palabra: "DEPLOY", pista: "Desplegar aplicación en producción" },
  { palabra: "VERSION", pista: "Número que identifica una edición del software" },
  { palabra: "GIT", pista: "Sistema de control de versiones distribuido" },
  { palabra: "REPOSITORIO", pista: "Lugar donde se almacena código fuente" },
  { palabra: "CONSTRUCTOR", pista: "Método especial para inicializar objetos" },
  { palabra: "DESTRUCTOR", pista: "Método que limpia recursos al eliminar objetos" },
  { palabra: "EXCEPCION", pista: "Error que puede ser manejado en tiempo de ejecución" },
  { palabra: "RECURSION", pista: "Función que se llama a sí misma" },
  { palabra: "VARIABLELOCAL", pista: "Variable que solo existe dentro de una función" },
  { palabra: "TIPODATO", pista: "Clasificación de datos como entero o cadena" },
  { palabra: "STACK", pista: "Estructura de datos LIFO (último en entrar, primero en salir)" },
  { palabra: "QUEUE", pista: "Estructura de datos FIFO (primero en entrar, primero en salir)" },
  { palabra: "BINARY", pista: "Sistema numérico base 2" },
  { palabra: "HEXAD", pista: "Sistema numérico base 16" },
  { palabra: "POINTER", pista: "Variable que almacena dirección de memoria" },
  { palabra: "MEMORIA", pista: "Espacio para almacenar datos e instrucciones" },
  { palabra: "COMPILADOR", pista: "Programa que traduce código a lenguaje máquina" },
  { palabra: "INTERRUPCION", pista: "Señal que altera el flujo normal del programa" },
  { palabra: "THREAD", pista: "Hilo de ejecución dentro de un proceso" },
  { palabra: "PROCESO", pista: "Programa en ejecución" },
  { palabra: "SYNCHRONIZE", pista: "Control para evitar conflictos en hilos" },
  { palabra: "SEMANTICA", pista: "Significado de las instrucciones en un lenguaje" },
  { palabra: "SINTAXIS", pista: "Reglas para escribir código correctamente" },
  { palabra: "COMPILACION", pista: "Proceso de traducción completa del código" },
  { palabra: "BINARYTREE", pista: "Estructura de datos en forma de árbol binario" },
  { palabra: "HASHMAP", pista: "Estructura para almacenar pares clave-valor" },
  { palabra: "ENCAPSULACION", pista: "Ocultar detalles internos en programación" },
  { palabra: "POLIMORFISMO", pista: "Capacidad de objetos para adoptar varias formas" },
  { palabra: "ABSTRACCION", pista: "Ocultar detalles complejos mostrando solo lo necesario" },
  { palabra: "MACHINELEARNING", pista: "Rama de la IA que permite aprender de datos" },
  { palabra: "DATAMINING", pista: "Extracción de información útil de grandes datos" },
  { palabra: "REDNEURONAL", pista: "Modelo inspirado en el cerebro para IA" },
  { palabra: "BIGDATA", pista: "Conjunto de datos tan grandes que requieren procesamiento especial" },
  { palabra: "APIREST", pista: "Estilo para diseñar servicios web" },
  { palabra: "SOCKET", pista: "Punto de conexión para comunicación en red" },
  { palabra: "CRYPTOGRAFIA", pista: "Estudio de técnicas para proteger información" },
  { palabra: "VIRTUALIZACION", pista: "Creación de recursos virtuales en un sistema" },
  { palabra: "CONTENEDOR", pista: "Unidad estandarizada para ejecutar aplicaciones" },
  { palabra: "DOCKER", pista: "Plataforma para crear y administrar contenedores" },
  { palabra: "KUBERNETES", pista: "Sistema para orquestar contenedores" },
  { palabra: "SERVERLESS", pista: "Modelo de computación en la nube sin servidor dedicado" },
  { palabra: "CACHE", pista: "Almacenamiento temporal para acelerar accesos" },
  { palabra: "COOKIE", pista: "Datos almacenados en navegador para sesiones" },
  { palabra: "TOKEN", pista: "Elemento que representa una autorización o acceso" },
  { palabra: "AUTENTICACION", pista: "Proceso para verificar identidad de usuario" },
  { palabra: "AUTORIZACION", pista: "Permiso para acceder a recursos específicos" },
  { palabra: "ENCRIPTACION", pista: "Proceso de convertir datos a código seguro" },
  { palabra: "DESARROLLO", pista: "Proceso de creación de software" },
  { palabra: "DEPURACION", pista: "Proceso de encontrar y corregir errores" },
  { palabra: "TESTING", pista: "Pruebas para asegurar calidad del software" },
  { palabra: "DOCUMENTACION", pista: "Información escrita sobre el software" },
  { palabra: "METODOLOGIA", pista: "Conjunto de métodos para organizar proyectos" },
  { palabra: "SCRUM", pista: "Marco de trabajo ágil para gestión de proyectos" },
  { palabra: "AGILIDAD", pista: "Capacidad para adaptarse rápido en desarrollo" },
  { palabra: "BACKEND", pista: "Parte del software que corre en el servidor" },
  { palabra: "FRONTEND", pista: "Parte del software que interactúa con el usuario" },
  { palabra: "FULLSTACK", pista: "Desarrollador que trabaja en frontend y backend" },
  { palabra: "CLOUD", pista: "Computación en servidores remotos por internet" },
  { palabra: "INFRAESTRUCTURA", pista: "Conjunto de recursos tecnológicos para soporte" },
  { palabra: "BASEDEDATOS", pista: "Sistema para almacenar y gestionar datos" },
  { palabra: "SQL", pista: "Lenguaje para manipular bases de datos relacionales" },
  { palabra: "NOSQL", pista: "Bases de datos no relacionales y flexibles" },
  { palabra: "INDEXACION", pista: "Técnica para acelerar búsquedas en bases de datos" },
  { palabra: "NORMALIZACION", pista: "Proceso para organizar datos en bases de datos" },
  { palabra: "JOIN", pista: "Operación para combinar tablas en bases de datos" },
  { palabra: "TRANSACCION", pista: "Unidad de trabajo que debe completarse íntegra" },
  { palabra: "CONSISTENCIA", pista: "Garantía de integridad en bases de datos" },
  { palabra: "ESCALABILIDAD", pista: "Capacidad para crecer sin perder rendimiento" },
  { palabra: "LATENCIA", pista: "Retraso en la transmisión de datos" },
  { palabra: "ANCHO", pista: "Cantidad de datos transmitidos por unidad de tiempo" },
  { palabra: "BANDA", pista: "Capacidad de transmisión en redes" },
  { palabra: "NODO", pista: "Punto de conexión en una red" },
  { palabra: "PROTOCOLO", pista: "Conjunto de reglas para comunicación entre dispositivos" },
  { palabra: "IP", pista: "Identificador único de un dispositivo en red" },
  { palabra: "DNS", pista: "Sistema que traduce nombres de dominio en IPs" },
  { palabra: "HTTP", pista: "Protocolo para transferencia de páginas web" },
  { palabra: "HTTPS", pista: "Versión segura de HTTP" },
  { palabra: "FTP", pista: "Protocolo para transferencia de archivos" },
  { palabra: "SSH", pista: "Protocolo seguro para administración remota" },
  { palabra: "SSL", pista: "Protocolo para comunicaciones seguras" },
  { palabra: "TOKENIZACION", pista: "Dividir texto en unidades para análisis" },
  { palabra: "ANALISIS", pista: "Proceso de examinar datos para extraer información" },
  { palabra: "BIG-O", pista: "Notación para medir eficiencia algorítmica" },
  { palabra: "OPTIMIZACION", pista: "Mejorar rendimiento o recursos usados" },
  { palabra: "DEPENDENCIA", pista: "Relación entre módulos o librerías" },
  { palabra: "CONCURRENCIA", pista: "Ejecución simultánea de tareas" },
  { palabra: "PARALELISMO", pista: "Ejecución de tareas al mismo tiempo físicamente" },
  { palabra: "SHELL", pista: "Interfaz de línea de comandos" },
  { palabra: "SCRIPT", pista: "Programa pequeño para automatizar tareas" },
  { palabra: "PIPELINE", pista: "Secuencia de procesamiento de datos" },
  { palabra: "CONTINUOUS", pista: "Integración y despliegue constante" },
  { palabra: "INTEGRACION", pista: "Unir partes de software para trabajar juntas" },
  { palabra: "DEPLOYMENT", pista: "Publicar software para uso real" },
  { palabra: "BACKUP", pista: "Copia de seguridad de datos" },
  { palabra: "RESTORE", pista: "Recuperar datos desde una copia de seguridad" },
  { palabra: "LOGGING", pista: "Registro de eventos del sistema" },
  { palabra: "MONITOREO", pista: "Vigilancia del funcionamiento del sistema" },
  { palabra: "ALERTA", pista: "Notificación de eventos importantes" },
  { palabra: "SCALEUP", pista: "Aumentar capacidad de un solo recurso" },
  { palabra: "SCALEDOWN", pista: "Reducir capacidad de un recurso" },
  { palabra: "SCALEOUT", pista: "Agregar más recursos iguales" },
  { palabra: "SCALEIN", pista: "Eliminar recursos agregados" },
  { palabra: "PROXY", pista: "Intermediario para solicitudes de red" },
  { palabra: "SCRUM", pista: "Marco ágil para gestionar proyectos complejos" },
  { palabra: "SPRINT", pista: "Periodo corto para completar un conjunto de tareas" },
  { palabra: "PRODUCTOWNER", pista: "Persona que define y prioriza el backlog" },
  { palabra: "SCRUMMASTER", pista: "Facilitador que ayuda al equipo a seguir Scrum" },
  { palabra: "BACKLOG", pista: "Lista priorizada de tareas o requisitos" },
  { palabra: "STANDUP", pista: "Reunión diaria corta para sincronización" },
  { palabra: "RETROSPECTIVA", pista: "Reunión para reflexionar y mejorar el proceso" },
  { palabra: "USERSTORY", pista: "Descripción breve de una funcionalidad desde el usuario" },
  { palabra: "KANBAN", pista: "Método visual para gestionar el flujo de trabajo" },
  { palabra: "VELOCIDAD", pista: "Medida del trabajo completado en un sprint" },
  { palabra: "INCREMENTO", pista: "Resultado usable y potencialmente entregable" },
  { palabra: "IMPEDIMENTO", pista: "Obstáculo que bloquea el progreso del equipo" },
  { palabra: "EPICA", pista: "User story muy grande que se divide en otras más pequeñas" },
  { palabra: "PLANIFICACION", pista: "Reunión para organizar el trabajo del sprint" },
  { palabra: "PRODUCTBACKLOG", pista: "Backlog general del producto" },
  { palabra: "SPRINTBACKLOG", pista: "Backlog de tareas específicas para el sprint" },
  { palabra: "AGILIDAD", pista: "Capacidad de adaptarse rápidamente a cambios" },
  { palabra: "METODOLOGIA", pista: "Conjunto de métodos para gestionar proyectos" },
  { palabra: "ITERACION", pista: "Ciclo repetido de trabajo para mejorar progresivamente" },
  { palabra: "COLABORACION", pista: "Trabajo conjunto para lograr objetivos comunes" },
  { palabra: "ENTREGA", pista: "Entrega de un producto funcional o mejora" },
  { palabra: "FEEDBACK", pista: "Retroalimentación para mejorar el producto o proceso" },
  { palabra: "PRIORIDAD", pista: "Orden de importancia de las tareas" },
  { palabra: "RESPONSABILIDAD", pista: "Compromiso con las tareas asignadas" },
  { palabra: "TRANSPARENCIA", pista: "Visibilidad total del progreso y problemas" },
  { palabra: "AUTOGESTION", pista: "Capacidad del equipo para organizarse sin supervisión" },
  { palabra: "SUSTENTABILIDAD", pista: "Capacidad de mantener un ritmo constante de trabajo" },
  { palabra: "REUNION", pista: "Encuentro para comunicación y toma de decisiones" },
  { palabra: "DEMO", pista: "Presentación del trabajo completado al final del sprint" },
  { palabra: "RISGO", pista: "Posibilidad de que ocurra un evento negativo" },
  { palabra: "ANALISIS", pista: "Estudio detallado para entender un problema o necesidad" },
  { palabra: "REQUIREMENTS", pista: "Requisitos o necesidades del producto" },
  { palabra: "DISEÑO", pista: "Planificación de la estructura y funcionamiento" },
  { palabra: "IMPLEMENTACION", pista: "Proceso de codificar y construir el producto" },
  { palabra: "PRUEBA", pista: "Verificación para asegurar calidad y funcionamiento" },
  { palabra: "DEPURACION", pista: "Proceso de encontrar y corregir errores" },
  { palabra: "DOCUMENTACION", pista: "Información escrita que explica el producto" },
  { palabra: "VERSIONAMIENTO", pista: "Gestión de diferentes versiones del software" },
  { palabra: "RELEASE", pista: "Publicación oficial de una versión del producto" },
  { palabra: "MANTENIMIENTO", pista: "Trabajo para corregir y mejorar el software" },
  { palabra: "COLABORATIVO", pista: "Enfoque que fomenta el trabajo en equipo" },
  { palabra: "COMUNICACION", pista: "Intercambio efectivo de información" },
  { palabra: "ADAPTABILIDAD", pista: "Habilidad para ajustarse a cambios" },
  { palabra: "MVP", pista: "Producto mínimo viable para validar ideas" },
  { palabra: "SUSTENTABLE", pista: "Que se puede mantener en el tiempo sin agotar recursos" },
  { palabra: "ARCHIVO", pista: "Unidad de almacenamiento de datos en disco" },
  { palabra: "BASEDEDATOS", pista: "Sistema para almacenar y gestionar información" },
  { palabra: "CLASEABSTRACTA", pista: "Clase que no puede ser instanciada directamente" },
  { palabra: "INTERACCION", pista: "Comunicación entre componentes o usuarios" },
  { palabra: "LENGUAJE", pista: "Sistema de comunicación utilizado para programar" },
  { palabra: "MALLA", pista: "Conjunto de nodos conectados en una red" },
  { palabra: "OBJETIVO", pista: "Propósito o meta a alcanzar en un proyecto" },
  { palabra: "PLATAFORMA", pista: "Entorno donde se ejecuta el software" },
  { palabra: "RUTINA", pista: "Conjunto de instrucciones para realizar una tarea" },
  { palabra: "SERVICIO", pista: "Funcionalidad accesible desde una aplicación" },
  { palabra: "TAREA", pista: "Unidad de trabajo asignada a un desarrollador" },
  { palabra: "USUARIO", pista: "Persona que utiliza el software o sistema" },
  { palabra: "VERSIONAMIENTO", pista: "Control y gestión de versiones del software" },
  { palabra: "WEBHOOK", pista: "Mecanismo para recibir notificaciones automáticas" },
  { palabra: "XML", pista: "Lenguaje para representar datos estructurados" },
  { palabra: "ZONA", pista: "Área específica en una red o sistema" },
  { palabra: "ACCESO", pista: "Permiso para utilizar recursos o datos" },
  { palabra: "AUTENTICACION", pista: "Proceso para verificar la identidad de un usuario" },
  { palabra: "BALANCEO", pista: "Distribución equitativa de carga en sistemas" },
  { palabra: "CACHE", pista: "Almacenamiento temporal para mejorar velocidad" },
  { palabra: "DEPENDENCIA", pista: "Relación entre componentes que dependen uno del otro" },
  { palabra: "ENTIDAD", pista: "Objeto o concepto que se modela en una base de datos" },
  { palabra: "FORMULARIO", pista: "Interfaz para ingresar datos en una aplicación" },
  { palabra: "GRUPO", pista: "Conjunto de usuarios o recursos organizados" },
  { palabra: "HOSTING", pista: "Servicio que permite alojar sitios web" },
  { palabra: "ICONO", pista: "Imagen representativa de una función o aplicación" },
  { palabra: "JERARQUIA", pista: "Organización en niveles de autoridad o importancia" },
  { palabra: "KEYLOGGER", pista: "Programa malicioso que registra teclas pulsadas" },
  { palabra: "LOGIN", pista: "Proceso de acceso a un sistema con usuario y contraseña" },
  { palabra: "MIGRACION", pista: "Traslado de datos o sistemas a otro entorno" },
  { palabra: "NODO", pista: "Elemento o punto dentro de una red" },
  { palabra: "OPTIMIZACION", pista: "Mejora del rendimiento o uso eficiente de recursos" },
  { palabra: "PLUGIN", pista: "Componente que añade funcionalidades a un software" },
  { palabra: "QUERY", pista: "Consulta para obtener datos de una base de datos" },
  { palabra: "RESPALDO", pista: "Copia de seguridad de datos o sistemas" },
  { palabra: "SEGURIDAD", pista: "Protección contra accesos no autorizados" },
  { palabra: "TOKEN", pista: "Elemento que representa autorización o acceso" },
  { palabra: "USABILIDAD", pista: "Facilidad de uso de una aplicación o sistema" },
  { palabra: "VALIDACION", pista: "Proceso de comprobar que los datos son correctos" },
  { palabra: "WIDGET", pista: "Componente gráfico en una interfaz de usuario" },
  { palabra: "XMLHTTP", pista: "Tecnología para intercambiar datos entre cliente y servidor" },
  { palabra: "ZIPPING", pista: "Compresión de archivos para reducir tamaño" },
  { palabra: "APIREST", pista: "Interfaz para comunicación entre sistemas vía HTTP" },
  { palabra: "BIBLIOTECA", pista: "Conjunto de funciones reutilizables en programación" },
  { palabra: "CONTENEDOR", pista: "Unidad que encapsula una aplicación y sus dependencias" },
  { palabra: "DEPLOYMENT", pista: "Proceso de poner un software en producción" },
  { palabra: "ENTORNO", pista: "Configuración donde se ejecuta una aplicación" },
  { palabra: "FIREWALL", pista: "Sistema que protege redes de accesos no autorizados" },
  { palabra: "GITHUB", pista: "Plataforma para alojar y gestionar código fuente" },
  { palabra: "HASHING", pista: "Transformación de datos en una cadena fija para seguridad" },

];
